
name: PR Unit Tests

# This tells the robot to ONLY wake up when someone asks to merge code (a Pull Request)
on:
  pull_request:
    branches:
      - main

jobs:
  test-and-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Unit Tests
        run: pytest test_app.py

      # This step ONLY happens if the test above FAILS. It sends the Slack message!
      - name: Notify Slack on Failure
        if: failure()  
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,author,workflow
          author_name: "Code Alarm!"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}